### ISSUE TITLE
Linux binaries for wx3.2

### ISSUE THREAD

**Issue by oleg68** [GrandOrgue/LoopAuditioneer#2]
I cannot run linux binaries from https://github.com/GrandOrgue/LoopAuditioneer/releases/download/v0.11.0/LoopAuditioneer-0.11.0-linux.x86_64.tar.gz on my Fedora40 system due lack of wxWidgets 3.0.

Could you also build executables for wxWidgets 3.2 as we do for grandorgue?

**Comment by larspalo** [comment]
It seems that GO adds the ppa:sjr/wx32 repository for building with a 3.2 wx version. To get an official wx 3.2 version one would need to use the ubuntu-24.04 runner. Which ubuntu runner would you like to have the wx 3.2 version of LoopAuditioneer built on?

**Comment by oleg68** [comment]
I don't recommend to use recent ubuntu runner because it will require a new glibc version that some distros with wx32 may not provide. So using a ppa is a better solution.

**Comment by larspalo** [comment]
> So using a ppa is a better solution.

Ok, that should be possible, but on ubuntu-20.04 or ubuntu-22.04 runner?

**Comment by oleg68** [comment]
> > So using a ppa is a better solution.
> 
> Ok, that should be possible, but on ubuntu-20.04 or ubuntu-22.04 runner?

20.04 gives more compatibility, so it would be better.

**Comment by larspalo** [comment]
@oleg68 At https://github.com/GrandOrgue/LoopAuditioneer/actions/runs/9766162226 there is a first successful attempt to build with wx32. Could you please test it?

**Comment by oleg68** [comment]
@larspalo Yes, I've tested it. It works

**Comment by larspalo** [comment]
@oleg68 Thanks for confirming!
